package httpapi

import (
	"context"
	"errors"
	"net/http"
	"strconv"
	"time"

	"github.com/coder/websocket"
	"github.com/coder/websocket/wsjson"
	"github.com/google/uuid"

	"github.com/maxjkfc/chiban/apps/api/internal/auth"
	"github.com/maxjkfc/chiban/apps/api/internal/chat"
)

type sendMessageRequest struct {
	Content string `json:"content"`
	// Generated by the client so a retry after a lost response resolves to the
	// message that already exists.
	ClientMessageID string `json:"client_message_id"`
}

type messageResponse struct {
	ID              string `json:"id"`
	GroupID         string `json:"group_id"`
	UserID          string `json:"user_id"`
	Type            string `json:"type"`
	Content         string `json:"content"`
	ClientMessageID string `json:"client_message_id"`
	CreatedAt       string `json:"created_at"`
}

type messagePageResponse struct {
	Messages []messageResponse `json:"messages"`
	// Before fetches the previous page; empty once history runs out.
	Before string `json:"before,omitempty"`
}

func newMessageResponse(m chat.Message) messageResponse {
	return messageResponse{
		ID:              m.ID.String(),
		GroupID:         m.GroupID.String(),
		UserID:          m.UserID.String(),
		Type:            m.Type,
		Content:         m.Content,
		ClientMessageID: m.ClientMessageID.String(),
		CreatedAt:       m.CreatedAt.UTC().Format(timeFormat),
	}
}

// sendMessageHandler posts a message over plain HTTP rather than the socket.
//
// The socket is one-directional on purpose: it delivers, it does not accept.
// That keeps one write path with one authorization check, and makes the
// persist-before-broadcast rule structural rather than a convention two code
// paths have to agree on.
func sendMessageHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		groupID, ok := pathUUID(w, r, "group_id")
		if !ok {
			return
		}

		var req sendMessageRequest
		if !decodeJSON(w, r, &req) {
			return
		}

		clientMessageID, err := uuid.Parse(req.ClientMessageID)
		if err != nil {
			writeError(w, http.StatusBadRequest,
				"client_message_id must be a UUID generated by the client", "client_message_id")
			return
		}

		message, err := d.Chat.Send(r.Context(), auth.UserFromContext(r.Context()).ID, groupID, chat.SendInput{
			Content:         req.Content,
			ClientMessageID: clientMessageID,
		})
		if err != nil {
			writeChatError(w, d, err)
			return
		}
		writeJSON(w, http.StatusCreated, newMessageResponse(message))
	}
}

func listMessagesHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		groupID, ok := pathUUID(w, r, "group_id")
		if !ok {
			return
		}

		limit := 0
		if raw := r.URL.Query().Get("limit"); raw != "" {
			parsed, err := strconv.Atoi(raw)
			if err != nil {
				writeError(w, http.StatusBadRequest, "limit must be a number", "limit")
				return
			}
			limit = parsed
		}

		page, err := d.Chat.History(r.Context(), auth.UserFromContext(r.Context()).ID,
			groupID, r.URL.Query().Get("before"), limit)
		if err != nil {
			writeChatError(w, d, err)
			return
		}

		out := messagePageResponse{
			Messages: make([]messageResponse, 0, len(page.Messages)),
			Before:   page.Before,
		}
		for _, m := range page.Messages {
			out.Messages = append(out.Messages, newMessageResponse(m))
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// chatSocketHandler streams a group's new messages to one connection.
//
// The handshake is an ordinary authenticated request, so the socket is behind
// the same session middleware as everything else, and membership is checked
// again here rather than trusted from whatever the client claims.
func chatSocketHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		groupID, ok := pathUUID(w, r, "group_id")
		if !ok {
			return
		}

		subscription, err := d.Chat.Subscribe(r.Context(), auth.UserFromContext(r.Context()).ID, groupID)
		if err != nil {
			writeChatError(w, d, err)
			return
		}
		defer subscription.Close()

		conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{
			// The browser origin is already the only one CORS allows; the
			// socket must not be laxer than the REST API.
			OriginPatterns: originPatterns(d.WebOrigin),
		})
		if err != nil {
			d.Logger.Error("websocket handshake failed", "error", err)
			return
		}
		defer conn.CloseNow()

		// Detached from the request context: the handshake's context is done
		// as soon as ServeHTTP returns, which would close the socket at once.
		ctx := conn.CloseRead(context.WithoutCancel(r.Context()))

		userID := auth.UserFromContext(r.Context()).ID

		for {
			select {
			case <-ctx.Done():
				return
			case message, open := <-subscription.Messages:
				if !open {
					return
				}

				// Membership is re-checked here, not just at the handshake: a
				// member who leaves while this socket is open must stop
				// receiving at once, and a failed check closes the connection
				// rather than assuming they are still allowed.
				allowed, err := d.Chat.MayReceive(ctx, userID, groupID)
				if err != nil {
					d.Logger.Error("chat membership re-check failed", "error", err)
					return
				}
				if !allowed {
					return
				}

				writeCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
				err = wsjson.Write(writeCtx, conn, newMessageResponse(message))
				cancel()
				if err != nil {
					// The reader is gone or too slow; history covers what they
					// miss when they reconnect.
					return
				}
			}
		}
	}
}

// originPatterns keeps the socket's allowed origin in step with CORS. An empty
// WebOrigin means tests, where the handshake comes from httptest's own host.
func originPatterns(webOrigin string) []string {
	if webOrigin == "" {
		return nil
	}
	return []string{stripScheme(webOrigin)}
}

func stripScheme(origin string) string {
	for _, prefix := range []string{"https://", "http://"} {
		if len(origin) > len(prefix) && origin[:len(prefix)] == prefix {
			return origin[len(prefix):]
		}
	}
	return origin
}

func writeChatError(w http.ResponseWriter, d Deps, err error) {
	var invalid chat.InvalidInputError
	switch {
	case errors.As(err, &invalid):
		writeError(w, http.StatusBadRequest, invalid.Message, invalid.Field)
	case errors.Is(err, chat.ErrNotMember):
		writeError(w, http.StatusForbidden, "you are not a member of this group")
	default:
		d.Logger.Error("chat request failed", "error", err)
		writeError(w, http.StatusInternalServerError, "internal error")
	}
}
