package httpapi

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"time"

	"github.com/coder/websocket"
	"github.com/coder/websocket/wsjson"
	"github.com/google/uuid"

	"github.com/maxjkfc/chiban/apps/api/internal/auth"
	"github.com/maxjkfc/chiban/apps/api/internal/chat"
	"github.com/maxjkfc/chiban/apps/api/internal/media"
)

type sendMessageRequest struct {
	Content string `json:"content"`
	// Generated by the client so a retry after a lost response resolves to the
	// message that already exists.
	ClientMessageID string `json:"client_message_id"`
	// Optional: makes this message a reply to another one in the same group.
	ReplyToMessageID string `json:"reply_to_message_id"`
	// Optional: posts an already-uploaded image or GIF instead of text.
	ChatMediaID string `json:"chat_media_id"`
}

type messageResponse struct {
	ID              string `json:"id"`
	GroupID         string `json:"group_id"`
	UserID          string `json:"user_id"`
	Type            string `json:"type"`
	Content         string `json:"content"`
	ClientMessageID string `json:"client_message_id"`
	CreatedAt       string `json:"created_at"`
	// Deleted messages keep their place with their content removed, so the
	// replies underneath them still make sense.
	Deleted bool `json:"deleted"`
	// Set on a meal card. The client fetches the meal by this id, which is what
	// keeps the card's contents subject to the meal's own authorization.
	MealRecordID string `json:"meal_record_id,omitempty"`
	// Set on an image or GIF message; the bytes are read from the media
	// endpoint, which decides who may see them.
	ChatMediaID string         `json:"chat_media_id,omitempty"`
	ReplyTo     *replyResponse `json:"reply_to,omitempty"`
	// Always present, so the client never has to guard against null.
	Reactions []reactionResponse `json:"reactions"`
}

type replyResponse struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Content string `json:"content"`
	Deleted bool   `json:"deleted"`
}

type reactionResponse struct {
	Type  string `json:"reaction_type"`
	Count int    `json:"count"`
	// Mine tells the client whether tapping again would remove it.
	Mine bool `json:"mine"`
}

// socketEvent is what the realtime feed pushes. One envelope with a kind, so
// adding a kind never changes how the client reads the ones it already knows.
type socketEvent struct {
	Type     string           `json:"type"`
	Message  *messageResponse `json:"message,omitempty"`
	Reaction *reactionEvent   `json:"reaction,omitempty"`
	// Set for a deletion. Only the id travels: a message carries per-reader
	// reaction state, which one broadcast cannot be right about for everyone.
	MessageID string `json:"message_id,omitempty"`
}

type reactionEvent struct {
	MessageID string `json:"message_id"`
	UserID    string `json:"user_id"`
	Type      string `json:"reaction_type"`
	Added     bool   `json:"added"`
}

func newSocketEvent(event chat.Event) socketEvent {
	switch event.Kind {
	case chat.EventMessage:
		message := newMessageResponse(event.Message)
		return socketEvent{Type: event.Kind, Message: &message}
	case chat.EventReaction:
		return socketEvent{Type: event.Kind, Reaction: &reactionEvent{
			MessageID: event.Reaction.MessageID.String(),
			UserID:    event.Reaction.UserID.String(),
			Type:      event.Reaction.Type,
			Added:     event.Reaction.Added,
		}}
	default:
		return socketEvent{Type: event.Kind, MessageID: event.MessageID.String()}
	}
}

type messagePageResponse struct {
	Messages []messageResponse `json:"messages"`
	// Before fetches the previous page; empty once history runs out.
	Before string `json:"before,omitempty"`
}

func newMessageResponse(m chat.Message) messageResponse {
	out := messageResponse{
		ID:              m.ID.String(),
		GroupID:         m.GroupID.String(),
		UserID:          m.UserID.String(),
		Type:            m.Type,
		Content:         m.Content,
		ClientMessageID: m.ClientMessageID.String(),
		CreatedAt:       m.CreatedAt.UTC().Format(timeFormat),
		Deleted:         m.Deleted,
		Reactions:       make([]reactionResponse, 0, len(m.Reactions)),
	}

	if m.MealRecordID != nil {
		out.MealRecordID = m.MealRecordID.String()
	}
	if m.ChatMediaID != nil {
		out.ChatMediaID = m.ChatMediaID.String()
	}
	if m.ReplyTo != nil {
		out.ReplyTo = &replyResponse{
			ID:      m.ReplyTo.ID.String(),
			UserID:  m.ReplyTo.UserID.String(),
			Content: m.ReplyTo.Content,
			Deleted: m.ReplyTo.Deleted,
		}
	}
	for _, r := range m.Reactions {
		out.Reactions = append(out.Reactions, reactionResponse{
			Type:  r.Type,
			Count: r.Count,
			Mine:  r.Mine,
		})
	}
	return out
}

// sendMessageHandler posts a message over plain HTTP rather than the socket.
//
// The socket is one-directional on purpose: it delivers, it does not accept.
// That keeps one write path with one authorization check, and makes the
// persist-before-broadcast rule structural rather than a convention two code
// paths have to agree on.
func sendMessageHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		groupID, ok := pathUUID(w, r, "group_id")
		if !ok {
			return
		}

		var req sendMessageRequest
		if !decodeJSON(w, r, &req) {
			return
		}

		clientMessageID, err := uuid.Parse(req.ClientMessageID)
		if err != nil {
			writeError(w, http.StatusBadRequest,
				"client_message_id must be a UUID generated by the client", "client_message_id")
			return
		}

		var replyTo *uuid.UUID
		if req.ReplyToMessageID != "" {
			parsed, err := uuid.Parse(req.ReplyToMessageID)
			if err != nil {
				writeError(w, http.StatusBadRequest,
					"reply_to_message_id must be a UUID", "reply_to_message_id")
				return
			}
			replyTo = &parsed
		}

		var chatMediaID *uuid.UUID
		if req.ChatMediaID != "" {
			parsed, err := uuid.Parse(req.ChatMediaID)
			if err != nil {
				writeError(w, http.StatusBadRequest,
					"chat_media_id must be a UUID", "chat_media_id")
				return
			}
			chatMediaID = &parsed
		}

		message, err := d.Chat.Send(r.Context(), auth.UserFromContext(r.Context()).ID, groupID, chat.SendInput{
			Content:          req.Content,
			ClientMessageID:  clientMessageID,
			ReplyToMessageID: replyTo,
			ChatMediaID:      chatMediaID,
		})
		if err != nil {
			writeChatError(w, d, err)
			return
		}
		writeJSON(w, http.StatusCreated, newMessageResponse(message))
	}
}

func listMessagesHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		groupID, ok := pathUUID(w, r, "group_id")
		if !ok {
			return
		}

		limit := 0
		if raw := r.URL.Query().Get("limit"); raw != "" {
			parsed, err := strconv.Atoi(raw)
			if err != nil {
				writeError(w, http.StatusBadRequest, "limit must be a number", "limit")
				return
			}
			limit = parsed
		}

		page, err := d.Chat.History(r.Context(), auth.UserFromContext(r.Context()).ID,
			groupID, r.URL.Query().Get("before"), limit)
		if err != nil {
			writeChatError(w, d, err)
			return
		}

		out := messagePageResponse{
			Messages: make([]messageResponse, 0, len(page.Messages)),
			Before:   page.Before,
		}
		for _, m := range page.Messages {
			out.Messages = append(out.Messages, newMessageResponse(m))
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// chatSocketHandler streams a group's new messages to one connection.
//
// The handshake is an ordinary authenticated request, so the socket is behind
// the same session middleware as everything else, and membership is checked
// again here rather than trusted from whatever the client claims.
func chatSocketHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		groupID, ok := pathUUID(w, r, "group_id")
		if !ok {
			return
		}

		subscription, err := d.Chat.Subscribe(r.Context(), auth.UserFromContext(r.Context()).ID, groupID)
		if err != nil {
			writeChatError(w, d, err)
			return
		}
		defer subscription.Close()

		conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{
			// The browser origin is already the only one CORS allows; the
			// socket must not be laxer than the REST API.
			OriginPatterns: originPatterns(d.WebOrigin),
		})
		if err != nil {
			d.Logger.Error("websocket handshake failed", "error", err)
			return
		}
		defer conn.CloseNow()

		// Detached from the request context: the handshake's context is done
		// as soon as ServeHTTP returns, which would close the socket at once.
		ctx := conn.CloseRead(context.WithoutCancel(r.Context()))

		userID := auth.UserFromContext(r.Context()).ID

		for {
			select {
			case <-ctx.Done():
				return
			case event, open := <-subscription.Events:
				if !open {
					return
				}

				// Membership is re-checked here, not just at the handshake: a
				// member who leaves while this socket is open must stop
				// receiving at once, and a failed check closes the connection
				// rather than assuming they are still allowed.
				allowed, err := d.Chat.MayReceive(ctx, userID, groupID)
				if err != nil {
					d.Logger.Error("chat membership re-check failed", "error", err)
					return
				}
				if !allowed {
					return
				}

				writeCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
				err = wsjson.Write(writeCtx, conn, newSocketEvent(event))
				cancel()
				if err != nil {
					// The reader is gone or too slow; history covers what they
					// miss when they reconnect.
					return
				}
			}
		}
	}
}

// originPatterns keeps the socket's allowed origin in step with CORS. An empty
// WebOrigin means tests, where the handshake comes from httptest's own host.
func originPatterns(webOrigin string) []string {
	if webOrigin == "" {
		return nil
	}
	return []string{stripScheme(webOrigin)}
}

func stripScheme(origin string) string {
	for _, prefix := range []string{"https://", "http://"} {
		if len(origin) > len(prefix) && origin[:len(prefix)] == prefix {
			return origin[len(prefix):]
		}
	}
	return origin
}

func writeChatError(w http.ResponseWriter, d Deps, err error) {
	var invalid chat.InvalidInputError
	switch {
	case errors.As(err, &invalid):
		writeError(w, http.StatusBadRequest, invalid.Message, invalid.Field)
	case errors.Is(err, chat.ErrNotMember):
		writeError(w, http.StatusForbidden, "you are not a member of this group")
	case errors.Is(err, chat.ErrNotFound):
		// One answer for "does not exist" and "not yours", matching the meal
		// and photo reads. A 403 here would confirm that a media_id someone
		// guessed is real, which is the one thing an opaque id is for.
		writeError(w, http.StatusNotFound, "not found")
	case errors.Is(err, chat.ErrNotAuthor):
		writeError(w, http.StatusForbidden, "you can only delete your own messages")
	default:
		d.Logger.Error("chat request failed", "error", err)
		writeError(w, http.StatusInternalServerError, "internal error")
	}
}

func deleteMessageHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		messageID, ok := pathUUID(w, r, "message_id")
		if !ok {
			return
		}

		if err := d.Chat.Delete(r.Context(), auth.UserFromContext(r.Context()).ID, messageID); err != nil {
			writeChatError(w, d, err)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

type reactionRequest struct {
	Type string `json:"reaction_type"`
}

func addReactionHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		messageID, ok := pathUUID(w, r, "message_id")
		if !ok {
			return
		}

		var req reactionRequest
		if !decodeJSON(w, r, &req) {
			return
		}

		if err := d.Chat.React(r.Context(),
			auth.UserFromContext(r.Context()).ID, messageID, req.Type); err != nil {
			writeChatError(w, d, err)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// removeReactionHandler takes the emoji from the path, as the API contract
// specifies. Nothing else identifies which of a user's reactions to drop.
func removeReactionHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		messageID, ok := pathUUID(w, r, "message_id")
		if !ok {
			return
		}

		if err := d.Chat.Unreact(r.Context(), auth.UserFromContext(r.Context()).ID,
			messageID, r.PathValue("reaction_type")); err != nil {
			writeChatError(w, d, err)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// availableReactionsHandler tells the client which emoji to offer, so the set
// lives in one place instead of being restated in the UI.
func availableReactionsHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, http.StatusOK, map[string][]string{"reaction_types": chat.Reactions})
	}
}

type chatMediaResponse struct {
	ID string `json:"id"`
	// Type is what was actually uploaded, decided by decoding rather than by
	// what the client claimed.
	Type string `json:"media_type"`
}

func uploadChatMediaHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		r.Body = http.MaxBytesReader(w, r.Body, media.MaxUploadBytes+(1<<20))

		if err := r.ParseMultipartForm(8 << 20); err != nil {
			writeError(w, http.StatusBadRequest,
				"request must be multipart/form-data within the size limit")
			return
		}
		defer r.MultipartForm.RemoveAll()

		file, header, err := r.FormFile("file")
		if err != nil {
			writeError(w, http.StatusBadRequest, "a file is required", "file")
			return
		}
		defer file.Close()

		if header.Size > media.MaxUploadBytes {
			writeError(w, http.StatusBadRequest,
				fmt.Sprintf("the file must be smaller than %d MB", media.MaxUploadBytes>>20), "file")
			return
		}

		data, err := io.ReadAll(io.LimitReader(file, media.MaxUploadBytes+1))
		if err != nil {
			writeError(w, http.StatusBadRequest, "could not read the uploaded file", "file")
			return
		}

		uploaded, err := d.Chat.UploadMedia(r.Context(), auth.UserFromContext(r.Context()).ID, data)
		if err != nil {
			writeChatError(w, d, err)
			return
		}
		writeJSON(w, http.StatusCreated, chatMediaResponse{
			ID:   uploaded.ID.String(),
			Type: uploaded.Type,
		})
	}
}

func getChatMediaHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		mediaID, ok := pathUUID(w, r, "media_id")
		if !ok {
			return
		}

		reader, contentType, err := d.Chat.OpenMedia(r.Context(),
			auth.UserFromContext(r.Context()).ID, mediaID)
		if err != nil {
			writeChatError(w, d, err)
			return
		}
		defer reader.Close()

		w.Header().Set("Content-Type", contentType)
		// The bytes behind a media id never change, but permission does: a
		// message can be deleted, or the reader can leave the group. An hour
		// keeps a scrolling chat from refetching every image while bounding
		// how long a device can render one it no longer has access to.
		w.Header().Set("Cache-Control", "private, max-age=3600")
		if _, err := io.Copy(w, reader); err != nil {
			d.Logger.Error("streaming chat media failed", "error", err)
		}
	}
}
