#!/usr/bin/env python3
"""Extract 吃 from Noto Serif TC 900 as an SVG path for the icon.

The character in direction D must not be typeset: a `<text>` element renders in
whatever CJK face the device happens to have, which on a machine with no
Chinese serif silently falls back to a plain sans. Storing the outline makes the
icon identical everywhere.

Noto Serif TC is SIL OFL 1.1, which permits derivative works. Run:

    pip install fonttools brotli
    python3 extract-glyph.py        # rewrites glyph.mjs
"""
import re
import subprocess
import sys
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

CHAR = "吃"
TTF = Path("NotoSerifTC-900.ttf")
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Noto+Serif+TC:wght@900&text=%E5%90%83"
)


def fetch() -> None:
    """Google Fonts serves a subset containing only the character we ask for."""
    css = subprocess.run(
        ["curl", "-sS", "-H", "User-Agent: Mozilla/5.0 Chrome/120", CSS_URL],
        capture_output=True, text=True, check=True,
    ).stdout
    match = re.search(r"url\((https://[^)]+)\)", css)
    if not match:
        sys.exit(f"no font url in the stylesheet:\n{css}")
    subprocess.run(["curl", "-sS", match.group(1), "-o", str(TTF)], check=True)


def main() -> None:
    if not TTF.exists():
        fetch()

    font = TTFont(TTF)
    glyphs = font.getGlyphSet()
    glyph = glyphs[font.getBestCmap()[ord(CHAR)]]

    # Font units with y already flipped, so the path drops straight into an SVG
    # user-space transform. The ink box is measured rather than assumed: the
    # ideographic square is not the same as the inked area.
    pen = SVGPathPen(glyphs)
    glyph.draw(TransformPen(pen, Transform(1, 0, 0, -1, 0, 0)))
    path = pen.getCommands()

    # Measure with a real pen. Reading coordinates out of the path string with a
    # regex silently mispairs them: H and V carry one coordinate, not two.
    bounds = BoundsPen(glyphs)
    glyph.draw(TransformPen(bounds, Transform(1, 0, 0, -1, 0, 0)))
    x_min, y_min, x_max, y_max = bounds.bounds
    cx, cy, w = (x_min + x_max) / 2, (y_min + y_max) / 2, x_max - x_min

    Path("glyph.mjs").write_text(
        f"// Generated by extract-glyph.py from Noto Serif TC 900 (SIL OFL 1.1).\n"
        f"// The character is an outline, not a font reference: it renders\n"
        f"// identically on a device with no Chinese serif installed.\n"
        f'export const CHI = "{path}";\n'
        f"// Places the glyph's ink box, size T, centred on (512, 512) of the\n"
        f"// 1024 canvas.\n"
        f"export const chiAt = (T) => {{\n"
        f"  const s = T / {w};\n"
        f"  return `translate(${{512 - {cx} * s}} ${{512 - ({cy}) * s}}) scale(${{s}})`;\n"
        f"}};\n"
    )
    print(f"glyph.mjs — ink box {w:.0f} wide, centre ({cx:.1f}, {cy:.1f})")


if __name__ == "__main__":
    main()
